### ISSUE TITLE
Media Volume Does Not Get Changed by the Volume Controls

### ISSUE THREAD

**Issue by Kethsar** [R-a-dio/R-a-dio-Amazing-Android-App#4]
As it is currently, I cannot change the media volume using my volume buttons when playing the stream. It works fine when we have it running as a service, but not as we have it currently. Should we try to fix that until we can figure out the service part?

**Comment by KilimIG** [comment]
are you on the master branch? everything's fine over here

**Comment by Kethsar** [comment]
Yes, on Master branch. Actually works fine on the musicplayer_service branch.

**Comment by Kethsar** [comment]
I take that back, it is working again. I do not know why, but when I tried to adjust the volume after hooking it up to an aux cable in my car, it would set the ringer volume instead. Probably not something we could figure out/fix, so I'll close this.

**Comment by KilimIG** [comment]
#justandroidthings
