### ISSUE TITLE
R/a/dio "stops" but does not "close"

### ISSUE THREAD

**Issue by KilimIG** [R-a-dio/R-a-dio-Amazing-Android-App#6]
on the musicplayer_service branch if you wipe the app from memory after initiating the service once you get the "R/a/dio has stopped" error.

to recreate the issue: 

open up the app -> hit play -> hit pause -> go back to your homescreen -> wipe the app from the recent apps screen -> receive error message

so it says that the app stopped but doesn't close?

**Comment by resttime** [comment]
@CaptainJet 
Reports no problem, so once you test for confirmation I suppose this can be closed.

**Comment by CaptainJet** [comment]
Fixed with #5
