### ISSUE TITLE
v1.1 release

### ISSUE THREAD

**Issue by KilimIG** [R-a-dio/R-a-dio-Amazing-Android-App#7]
# for the release of 1.1 based on user feedback, i'll be making this issue, please reply back on what you think is easy/feasible for you to complete

- More transparent searching (searching... etc) **COMPLETE**
- Change the song in the Queue to be a lighter shade of blue if requested **COMPLETE**
- More notification support **IN PROGRESS**
- On unplugging headphones have the app auto-pause (This is in higher SDKs automatically but lower SDKs needs it coded manually)
- Chromecast integration oh boy
- DJ Theme??? idk this is kind of dependent on the new site but it would be nice
- People from Brazil can still download the app, have it so they can't
- Back button **COMPLETE**
- Copying currently playing songs easier + q/lp **COMPLETE**
- Lower the font on NP so it doesn't scroll that much **COMPLETE**
- gay ass ricing because we have nothing better to do

**Comment by KilimIG** [comment]
hi wessie XD pls reply

**Comment by KilimIG** [comment]
XD

**Comment by KilimIG** [comment]
HOW DO I STOP MYSELF FROM GETTING EMAILS

**Comment by Kethsar** [comment]
Queue song colour based on whether it is a request or not can be done fairly easily. In the song's JSON object is a property called "type." 1 is a request, 0 is auto-added by Hanyuu.

Pause on headphone unplug is also feasible and simple and probably should have been put in version 1.0 but I was too lazy.

People from Brazil downloading is on Google and their shitty Play Store or them grabbing the APK from the site. I do not know how feasible blocking the country would be internally.

DJ theme is included in the gay ass ricing step if we get there.

Chromecast integretion hell if I know ¯\_(ツ)_/¯

**Comment by CaptainJet** [comment]
Chromecast is a HUGE pain, I'd rather not target including it in 1.1

**Comment by KilimIG** [comment]
added something else in, when you tap+hold on the nowplaying box it will automatically copy the text to the clipboard in addition to announcing via Toast Notification (text copied to clipboard)

**Comment by resttime** [comment]
For tap+hold it can be simply done by overriding the OnLongClickListener for each textview we want this enabled for.

**Comment by KilimIG** [comment]
pretty sure it's just the np for now, of people ask for it we can apply it
to the LP/q im sure

**Comment by KilimIG** [comment]
1.1 pushed and closed ezpz
