### ISSUE TITLE
on the road to 1.2 (more like 1.15 because we're dumb)

### ISSUE THREAD

**Issue by KilimIG** [R-a-dio/R-a-dio-Amazing-Android-App#8]
babby's first null pointer edition

- FIX NULL POINTER THANKS CAPTAINJET

- when you start playback via another audio app it should stop the audio service for this app,  and when you start the service from our app it should start other audio services currently active

- further gay ricing (rest pls)

**Comment by CaptainJet** [comment]
point one and two fixed in 40fcd53f2c074cbe00db76988c73a8e25be8ef86

**Comment by Kethsar** [comment]
1.1.1 is more like it. 1.15 would imply 15th minor release of version 1.

**Comment by KilimIG** [comment]
just found this from Nao

http://imgur.com/a/zILn4

**Comment by Kethsar** [comment]
Were they running the latest version?

Do we need to put a god damn update checker in our app?

**Comment by KilimIG** [comment]
that was taken from 1.1, on Android 4.4.2

i had  a similar issue while beta testing but uh, woops

it's entirely plausible that lower SDKs do not have the color function for
buttons, which means we'd have to make/call our own drawable or just opt
for boring colors

**Comment by resttime** [comment]
3rd issue should be fixed with e1d073f398b836b46607731d85b1ba39876dbe20

**Comment by KilimIG** [comment]
fucking aced
