### ISSUE TITLE
on the road to 1.2

### ISSUE THREAD

**Issue by KilimIG** [R-a-dio/R-a-dio-Amazing-Android-App#9]
here's a list of what should/could be on 1.2

- Bluetooth tags

- continuous scroll for songs that return more than 20 results (but there should be a cap so you don't return that much, maybe 60?)

- Chromecast support to be worked on exclusively by captain jet

- gay ass ricing

**Comment by resttime** [comment]
Part of Bluetooth tags is worked on but it's not done.

It might be necessary to move API update code from the MainActivity into the RadioService to complete the rest of it because there's no way to know when the tags change in the RadioService. Would also mean having to implement some way for the MainActivity to be notified of API update in the RadioService. Probably using the PlayerState class and a broadcast. Would also mean that we would now be able to show the tags in the notification too.

I suppose it might be possible to move the code for Bluetooth tags into the MainActivity. Restricts the feature only if the MainActivity is active and simpler since it's hooking into previous functionality.

Which one?

**Comment by KilimIG** [comment]
the latter sounds easier and faster lol so id go with that? we'd need to poll the others to really make a decision

**Comment by resttime** [comment]
Kk, it's really a kind of the functionality vs complexity trade off. I don't mind either way.

Until then and for reference: ways to do the second thing I mentioned is stuffing the PlayerState class with the tags and then sending a new intent to the RadioService. I guess alternatively one could just package the tags in the intent too.

In that case I just realized that it might be possible to have the notification can be updated to show tags the same way too, it'll just be restricted to work only when the MainActivity is open as well.

**Comment by resttime** [comment]
Screw it, went with second option. Can always be changed later. Bluetooth tags should now theoretically work.

**Comment by KilimIG** [comment]
oh sweet but how do we test this lol

when im home I'll pull and see if it works in my car i guess?

**Comment by KilimIG** [comment]
heya rest sorry it took so long to test everything

okay so it doesnt work :-(

it just says no data provided

**Comment by resttime** [comment]
Pushed some changes, hopefully this works.

**Comment by Kethsar** [comment]
I added pages to the Search list. That took me a lot longer than I thought once I changed out the dots from a static text view to buttons to be used when they could be. Fucking hell I feel retarded.

**Comment by KilimIG** [comment]
alrighty bluetooth tags work perfectly fine for me, thanks rest. however can anyone else test this in their car? dunno if my device is any different

kethsar also has pagination with searches but he forgot to tell me to pull so i didn't test that out, will do when home

also any ideas for gay ricing?

**Comment by resttime** [comment]
Theory is strong hehehe, I'm glad it works.

As for ricing I suppose picking something from #2? I think a thing people did request was some kind of scheduling for playback for alarms?  The app is becoming quite feature complete at this point so I dunno.

**Comment by Albrektson** [comment]
Connecting to a bluetooth reciever and starting playback with the app will leave old playback data (song name, etc.) from spotify/youtube/whatever showing on the reciever until the current song ends and a new song starts in the app.

**Comment by resttime** [comment]
I believe the Bluetooth issue should be simple to fix. I'm fairly pretty busy as of late so hopefully I'll get to it eventually.

**Comment by resttime** [comment]
Bluetooth issue fixed by @Kethsar with d8ec74eed163f9fe2eee512d7a00a816ff751876 and a49bc7df64387085f8046932ce77c062d3faeafa

**Comment by Kethsar** [comment]
tbh everything here that can be done has been done.
